### ISSUE TITLE
Would it make sense to add the host option?

### ISSUE THREAD

**Issue by scart88** [cuber-cloud/cuber-gem#8]
# Would it make sense to add a host option?
This will work perfectly with the DigitalOcean LoadBalancer, providing a HTTPS SSL certificate with their official NGINX Ingress Controller and Cert-Manager.

#### Cuberfile
```ruby
ingress true
host 'example.com'
```

#### cuberfile_parser.rb
```ruby
def initialize
  @app = nil
  @host = nil
  ....
      
  def host name
    @host = name
  end
```

#### cuberfile_validator.rb
```ruby
def validate
  ...
  validate_host
  ...

def validate_host
  @errors << 'host name must be present' if @options[:host].to_s.strip.empty?
end 
```

#### deployment.yml
```Yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: <%= @options[:app] %>
  labels:
    app.kubernetes.io/name: <%= @options[:app].to_s.to_json %>
    app.kubernetes.io/instance: <%= @options[:instance].to_s.to_json %>
    app.kubernetes.io/version: <%= @options[:release].to_s.to_json %>
    app.kubernetes.io/managed-by: cuber
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
    <%- @options[:lb].each do |key, value| -%>
    <%= key %>: <%= value.to_s.to_json %>
    <%- end -%>
spec:
  <%- if @options[:ssl] -%>
  tls:
  - hosts:
    - <%= @options[:host] %>
    secretName: letsencrypt-nginx
  <%- end -%>
  rules:
  - host: <%= @options[:host] %>
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 8080
```

#### cert_manager_issuer.yaml
```yaml
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-nginx
  namespace: <%= @options[:app].to_s.to_json %>
spec:
  # ACME issuer configuration
  # `email` - the email address to be associated with the ACME account (make sure it's a valid one)
  # `server` - the URL used to access the ACME server’s directory endpoint
  # `privateKeySecretRef` - Kubernetes Secret to store the automatically generated ACME account private key
  acme:
    email: 'email address'
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
      # Use the HTTP-01 challenge provider
      - http01:
          ingress:
            class: nginx
```
